language: go
go:
  - 1.7
services:
  - docker
env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "EmNOhPYUAufbbBd/T1hCw0+EHiczicj6MPZHFtyZlsbn0Kvc2EPtKL/br2b87sMxe4IHo8rXybQ0lFcZkaLvA5UFEZELyL2knJaCZtCdc8wYe16aWVk47apTpCSqD2q1URQ/NM7cyJ1UA51pbxgQo5gYuWj6kQ6R+Xv1XJAeUp5/kOoZGtS7/Lo54pR6kBIFBNzi7CxX5AT6L6tmvhvmoKv6SjPvY95K2Tj/h21827u9jpE1qYdjhVsGhCWTTNYEuE0nR8eeicYJQYIprqMsKmU/pP0NwOWjmwE99zniaBwgWXLVkODtcwlCQlyGYYys+m8nK4Bki9v+yviVc81OiDJ4vMSHKOAksIOQ99pXeUkb/tv/ib9qp1g+4ndqZmhq0S85hgADKkRi3cIOXsm7JD7T6I4xKpleCOb+vtQ1gtmv1T2DrSXYogtDmUxnh4uk8UngL5nHO9uEUOU8bQMztECSWoSc5AWrLt7YPVdHo/DfBiDb1QcpSnXu6ayLpwkOjgtewwrdAkVn+/Wd0JK/IF9OccuFc0un4H+RqA8MjcCKteXbyHc3XQ7SZiSiM7l+tuPZfQSKwiNnDREQYesz9EupG9m6RULzbu1pIqfQlUNcSCVhedC5TGq6Qk4WOdoEMzg5vLLaY4+PI/pvl808zdko+TuQqCbHUMIu2hTbKxI="
    # AWS_SECRET_ACCESS_KEY
    - secure: "ygP+HsX6PY4MmrvJF7efSNEprW71h09StQSww4U/lDRAzb0HvU5U9KBdpsbRmllKb7ymezIt16/sNbPbdbMNfLBZIIKu/pbsfoJa3jft5oArtqUM1pHd+K8sF/yUa07anZXB+s6je5Yok1ymF1Tm2oBZsnj1TK0PYaI/OVhGXnSp904u3qzNCK9CdzvAebYztn13+GcaFw8dDd6xK7P4edmw9R7iJ/TD3RTMDDrYnJrkq023e7IEldxWaezrRWilGC+1bAMyKbvNL0i0OLbgHPQuxcS2oiofY7dJhMqnHyhzRxL6nYtJDBQG6ZUfM1O+ksEHL/P8yvFBXVY/IpTW7fgml1oVzQOz9oX3MzlNi8Lblx57JNXMsvC6IeKZ9EeNEYUcaPkaJ0LdjBkJPKQRpNepOkSZ1jriASExrdn5ZJmbWvQ3/wvV0Ry5RT0oMwA6SSZ0wp9bowodi3yuQSJUDHfO0cIeawl7V7NY9npBVRGZnDaQ7N0YgUoM5n5z9AJndvClAPsg50gqoIMOeoabOquhPEHpVwUBV+fZZVfhlm0Ggi1PCRfjkAD+VZiaqLmKKy4xAU+ls/hIFK1D9xjycyb/YaR6ha83uWKxeHoaa34NiuZViJ7jXCQdwF5mhXakROWLsyioaCePNO51SfnUkEFGfsOwDzODQbBu2Rub6kw="
    # DISTRIBUTION_ID
    - secure: "r37ZJGkB+E3LzCnjf1xhtXr04mHXcNs/Q4L9WqghMhchZ4w5XnDJ4NOEjieq50OC2p/lwGZKoZ0roxDyvs4gaUdaPC9RgtmqUpsniFdnWnX+Zkn6PEoQ+luchlo5qllVohKWoIraQtdYZXyEQKI2aRV5wxsBKkDPUbxaGXbOXSP6MVuUURYa6GxSkoz8sswWWwCdhlAzm7cWIQFRkZDL+ZjnYO8UrAa/zf+oGKpVsw5BREeuU2NtQrV/TJ6xfGd1qm8mC4qv5ijluRcAbbKh2CczHAVy9uQ12ZEZHHeN1JPhKBtHy/gQCKO8ZFlce6IuD+/wQ8rq6wY2IKLqc8nC485gpWIZ942dooahIjPPpk02YHbaj31C54nA1WvnlKhFQwnP1bJrFiGblMHfT44B7SZFzXP+InMKi+OnUZtvUOMFsiyaXMrLsUcaY91TQtiLOlwUSEhk8vZWsJ65sF4OvKX8oUvK2g5TKzR8uiMOM8D1AX8cwPRXaK6VzEJwsXoLOA3GgIxp90AZhYWWbkCwUA25KcAP0QlncEdSxkpPd3ypYluYIcEHxqPEeP11Ohj6YUD/92rPTwa6TCoB2K9tMg3JsW+4kFD8vrdTHzUrNzmsKKLOx1bF+DVuOf0rNtHPCqIBZj0dz6MNbwug6Xak6S47FG1DRIs78o8HlNspzTw="
    - HUGO_VERSION=v0.18.1
install:
  - ./scripts/install_hugo.sh
script:
  - hugo
before_deploy:
  - pip install awscli
  - aws configure set preview.cloudfront true
deploy:
  - provider: script
    script: aws s3 sync public s3://me.kalbas.it
    skip_cleanup: true
    on:
      repo: "kalbasit/me.kalbas.it"
      branch: "master"
after_deploy:
  - aws cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID}" --paths "/*"
