language: go
go:
  - 1.7
services:
  - docker
env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "dj+0CL0YNxyI69VXOUXxPUgAq/UEWTw1P8pRl/YGA17Scsraj/r7sSQU/Mu7IfX1CQy3GkqRtTEc9MTlnbSb6aFlz7LZlXyXG6dtynUzh06OtjxK1seeFCnTLWn51IXWFm5YALTWULHNF22lL3gV5MfYwrdMXigfN1V05bEBX451IqGBXbLiuNE3iW28ztJTT4itrGmaFRWpSFlENkHODgeiUPJbk+8Un6eWbP8rIKwhDNtr6AXcfaryWmDsdf0pTAqR2+o8VBz6/vwLkiLFAgF9HwoSKvQX/B1RI819Z6LhyYHm2dFSO/kT44vs4298rjFuXQJzd3mNA5sQK04sonUd4moEKoLuxCC3+mrNhYq9jgOSOMC/ZATXoNZl5L81BV/caUOTKXu3SdZOTLD5frIV8qtY5m1Xeo6JsjDdf7fVAa7grP9e2+2OHe1G4S/WxrpwFvpA7XM/Bozo29LLqlI6pI3YuAv0XGFjw00p5NSA7+Qvjal7tvvB52n+TOZ+BumFR3E58djfV2DSi2ocvT1b95yXhF2incYOHZIVtmMsfE13UdkidRBcso316o/8cFVjVCPfzrQIbQZ8KTLUhXOoLyqJRBHJsby5gh6PXmUvzWCitV1W9SIsn9XoHgljlVOkxfD3AYDykSgEtAouncD1Xw1zRgNAJSFQ9ACB7SI="
    # AWS_SECRET_ACCESS_KEY
    - secure: "wLZwmcaQbtMX3CJuG2sgHp+VD8X/WCed8cASAGwL+Ao8Th0ExPGxKO2ypQq9cVpUvKFyTRV4PLM2G2vdoLssq2uPavaygH+5iAnsppl7FR3b4ykw3IczS8U6IJMFVbEeM1OpmIiGDgYbU9Oo6v0P5akIN93Pnthf1n9OHbMvPVs/tlGZPJw24YkG+y6t5hbL00rCpaA8vNxpH2QwhuG4ugUa0Dq5CAhyMnXqe5P9q3oBKBQ9oyaCwVwidvXgjyD5eJ89tQkVpjwqscP9M4dOGSlHbuF6E/QnmbHksiSKWjs779e80F4Wscf9fuX78XnlUpo8lrOf6NkRt05ER7JUq8NjvuEPe0kDCW9jGQTSrCcbf2dr/ycUt11COQpn4XEaPqLRYXHkLWIvKOnGJUiutkgcccKXozFVEhGwf9CtTVFQObdIsXNdbnZqLN/zCUm+JIrJYulAiRr/gl01GX6skHZl5pkpQuTsiBocHaGEm57DjAynnSZc9LeY2GhRVzIj6H6BvxfQmrshjhUvGBit+bGudoYCnIn91yr7TwoVjZXObcZOcfk1vHFP7R6JKeqjdtneY59AcF/2Pp+Q6L6uaZXasEYBPDPHHV3d4Pi4urfkahSVKu4Z7ezyYySTFKyK+HDIbpOZlB81OoIrmlNYA3aAYqW8v3JvoAImEVhdlrc="
    - HUGO_VERSION=v0.18.1
install:
  - ./scripts/install_hugo.sh
script:
  - hugo
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: me.kalbas.it
    acl: private
    local_dir: public
    skip_cleanup: true
    on:
      repo: "kalbasit/me.kalbas.it"
      branch: "master"
